### ISSUE TITLE
NO PRICE IN THE CROSSES LOCATION

### ISSUE THREAD

**Issue by lecatos** [ao-data/albiondata-client#43]
PRICES IN LOCATION SUCH AS MOUNTAIN CROSS, SWAMP CROSS, STEPE CROSS AND FOREST CROSS DOESN'T EXIST IN THE API. PLEASE UPDATE YOUR CLIENT/API TO SUPPORT IT. THANKS

**Comment by phendryx** [comment]
There is data for those. https://www.albion-online-data.com/api/v2/stats/history/T4_BAG?date=2-5-2020&end_date=2-12-2023&locations=0004 for example. 0004 is Swamp Cross (https://github.com/ao-data/ao-bin-dumps/blob/master/formatted/world.json#L56). Just because there isn't current data for them doesn't mean they don't work. The data is crowd sourced, so if people aren't scanning those markets with the client, then there won't be any current data and historical data will have holes.
