### ISSUE TITLE
Windows Defender and virustotal falgging the .exe file

### ISSUE THREAD

**Issue by Xx0ME0xX** [ao-data/albiondata-client#83]
What is the cause of this? Would it just be because it collects data from albion in the background? Windows wouldn't let me install it, it just blocked it.

**Comment by phendryx** [comment]
It's probably because it's literally sniffing the traffic stream for the Albion Online game UDP port. There's not a lot that I can do about it because without sniffing the UDP port, there's no point in the client and I'm sure there's too much effort into going to each antivirus company and proving that it's not malware, for each compiled version that gets released.

Either add an exclusion for the data client or don't use it if you don't trust it. The code is 100% open, the build you download is compiled via github actions and you can view each step of the way from code to .exe. You can download the code and build it yourself if you wish. If for some reason you still don't trust it, that's fine too.
